### ISSUE TITLE
сильное заявление

### ISSUE THREAD

**Issue by Skoowshot** [hoprik/CsgoCase#1]
хочу высказаться, что хоприк убил мне жизнь своим существованием. Данный человек нарушил статьи 190 и 298 сказав об этом публично Владимиру Владимировичу Путину, Данный человек, по моему мнению, является членом экстремисткой организации ЛГБТ и ЧВК "Вагнер", я требую посадить данного человека и все его проекты в корзину.

**Comment by hoprik** [comment]
Хоприк 1: Alxart 0
